import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import ModalProvider from '@/providers/modalProviders';
import ToastProvider from '@/providers/toastProvider';
import '@css/globals.css';
import { cn } from '@lib/utils';
import prisma from '@/lib/prismadb';

import Navbar from '@/components/navigation/navbar';
import PageContainer from '@/components/page-container';

const fontSans = FontSans({
	subsets: ['latin'],
	variable: '--font-sans'
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const collections = await prisma.collection.findMany({
		include: {
			billboard: true
		}
	});

	return (
		<ClerkProvider>
			<html lang='en'>
				<body className={cn('bg-background font-sans antialiased', fontSans.variable)}>
					<ModalProvider />
					<ToastProvider />
					<Navbar collections={collections} />
					<PageContainer>{children}</PageContainer>
				</body>
			</html>
		</ClerkProvider>
	);
}
