import type { Metadata } from 'next';
import { ClerkProvider } from '@clerk/nextjs';
import ModalProvider from '@/providers/modalProviders';
import { Inter as FontSans } from 'next/font/google';
import '@css/globals.css';
import { cn } from '@lib/utils';

const fontSans = FontSans({
	subsets: ['latin'],
	variable: '--font-sans'
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<ClerkProvider>
			<html lang='en'>
				<body className={cn('bg-background font-sans antialiased', fontSans.variable)}>
					<ModalProvider />
					{children}
				</body>
			</html>
		</ClerkProvider>
	);
}
